# Generated by Django 4.2.5 on 2023-09-09 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_alta', models.DateField()),
                ('fecha_actualizacion', models.DateField()),
                ('potencia_actual', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusDispositivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('potencia_actual', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('id_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dispositivo')),
                ('id_tipoDispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipodispositivo')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='id_statusDispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.statusdispositivo'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='id_tipoDipositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipodispositivo'),
        ),
    ]
